2023-02-03 10:52:07 info cfgInit.doInit:cfgInit.java:776 booting
2023-02-03 10:52:07 info cfgInit.doInit:cfgInit.java:958 initializing hardware
2023-02-03 10:52:07 info cfgInit.doInit:cfgInit.java:964 applying defaults
2023-02-03 10:52:09 info cfgInit.doInit:cfgInit.java:985 applying configuration
2023-02-03 10:52:09 info cfgInit.doInit:cfgInit.java:1020 boot completed
2023-02-03 10:53:02 info cfgInit.doInit:cfgInit.java:776 booting
2023-02-03 10:53:03 info cfgInit.doInit:cfgInit.java:958 initializing hardware
2023-02-03 10:53:03 info cfgInit.doInit:cfgInit.java:964 applying defaults
2023-02-03 10:53:05 info cfgInit.doInit:cfgInit.java:985 applying configuration
2023-02-03 10:53:05 info cfgInit.doInit:cfgInit.java:1020 boot completed
2023-02-03 14:48:12 warning userLineHandler.doExec:userLine.java:875 <nobody> configuring from local:telnet <loop> 23 -> 127.0.0.1 56990
2023-02-03 14:48:23 warning userLineHandler.doExec:userLine.java:907 <nobody> configured from local:telnet <loop> 23 -> 127.0.0.1 56990
2023-02-03 14:48:27 warning rtrIsisNeigh.readHelloTlvs:rtrIsisNeigh.java:644 neighbor level2 10.0.23.0 up
2023-02-03 14:48:49 warning rtrIsisNeigh.readHelloTlvs:rtrIsisNeigh.java:644 neighbor level2 10.0.34.1 up
2023-02-03 15:58:03 info cfgInit.doInit:cfgInit.java:776 booting
2023-02-03 15:58:03 info cfgInit.doInit:cfgInit.java:958 initializing hardware
2023-02-03 15:58:03 info cfgInit.doInit:cfgInit.java:964 applying defaults
2023-02-03 15:58:05 info cfgInit.doInit:cfgInit.java:985 applying configuration
2023-02-03 15:58:06 info cfgInit.doInit:cfgInit.java:1020 boot completed
2023-02-03 15:58:06 warning rtrIsisNeigh.readHelloTlvs:rtrIsisNeigh.java:644 neighbor level2 10.0.34.1 up
2023-02-03 15:58:06 warning rtrIsisNeigh.readHelloTlvs:rtrIsisNeigh.java:644 neighbor level2 10.0.23.0 up
2023-02-03 15:58:54 warning userLineHandler.doExec:userLine.java:875 <nobody> configuring from local:telnet <loop> 23 -> 127.0.0.1 58056
2023-02-03 15:58:59 warning userLineHandler.doExec:userLine.java:907 <nobody> configured from local:telnet <loop> 23 -> 127.0.0.1 58056
